# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PrzechwycWysokosc
                                 A QGIS plugin
 Pozwala na sprawdzenie wysokości terenu w danym punkcie na podstawie API GUGiK NMT
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-10-15
        copyright            : (C) 2025 by Michał Włoga - EnviroSolutions Sp. z o.o.
        email                : office@envirosolutions.pl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
import os


PLUGIN_VERSION = ''
PLUGIN_NAME = ''
with open(os.path.join(os.path.dirname(__file__), 'metadata.txt'), 'r') as pluginMetadataFile:
    for line in pluginMetadataFile.readlines():
        if line.startswith("version="):
            PLUGIN_VERSION = line.strip().split('=')[-1]
        if line.startswith("name="):
            PLUGIN_NAME = line.strip().split('=')[-1]

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PrzechwycWysokosc class from file PrzechwycWysokosc.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .przechwyc_wysokosc import PrzechwycWysokosc
    return PrzechwycWysokosc(iface)
