# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'przechwyc_wysokosc_dockwidget_base.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PrzechwycWysokoscDockWidgetBase(object):
    def setupUi(self, PrzechwycWysokoscDockWidgetBase):
        PrzechwycWysokoscDockWidgetBase.setObjectName("PrzechwycWysokoscDockWidgetBase")
        PrzechwycWysokoscDockWidgetBase.resize(281, 383)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(5, 0, 5, 0)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_copyrights = QtWidgets.QLabel(self.dockWidgetContents)
        self.lbl_copyrights.setTextFormat(QtCore.Qt.RichText)
        self.lbl_copyrights.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_copyrights.setOpenExternalLinks(True)
        self.lbl_copyrights.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.lbl_copyrights.setObjectName("lbl_copyrights")
        self.horizontalLayout_2.addWidget(self.lbl_copyrights)
        self.label_5 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_5.setMaximumSize(QtCore.QSize(20, 20))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/plugins/przechwyc_wysokosc/drzewiec.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.gridLayout.addLayout(self.horizontalLayout_2, 21, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_4 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_4.setMaximumSize(QtCore.QSize(50, 50))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/plugins/przechwyc_wysokosc/icon_pw2.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.gridLayout.addLayout(self.horizontalLayout, 7, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 8, 0, 1, 1)
        self.captureButton = QtWidgets.QPushButton(self.dockWidgetContents)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/plugins/przechwyc_wysokosc/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.captureButton.setIcon(icon)
        self.captureButton.setObjectName("captureButton")
        self.gridLayout.addWidget(self.captureButton, 13, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 10, 0, 1, 1)
        self.coordsEdit = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.coordsEdit.setEnabled(True)
        self.coordsEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.coordsEdit.setObjectName("coordsEdit")
        self.gridLayout.addWidget(self.coordsEdit, 9, 0, 1, 1)
        self.copyButton = QtWidgets.QPushButton(self.dockWidgetContents)
        self.copyButton.setObjectName("copyButton")
        self.gridLayout.addWidget(self.copyButton, 12, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 15, 0, 1, 1)
        self.heightEdit = QtWidgets.QLineEdit(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.heightEdit.setFont(font)
        self.heightEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.heightEdit.setObjectName("heightEdit")
        self.gridLayout.addWidget(self.heightEdit, 11, 0, 1, 1)
        self.lbl_pluginVersion = QtWidgets.QLabel(self.dockWidgetContents)
        self.lbl_pluginVersion.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_pluginVersion.setObjectName("lbl_pluginVersion")
        self.gridLayout.addWidget(self.lbl_pluginVersion, 17, 0, 1, 1)
        self.lbl_email = QtWidgets.QLabel(self.dockWidgetContents)
        self.lbl_email.setTextFormat(QtCore.Qt.RichText)
        self.lbl_email.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_email.setOpenExternalLinks(True)
        self.lbl_email.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.lbl_email.setObjectName("lbl_email")
        self.gridLayout.addWidget(self.lbl_email, 22, 0, 1, 1)
        PrzechwycWysokoscDockWidgetBase.setWidget(self.dockWidgetContents)

        self.retranslateUi(PrzechwycWysokoscDockWidgetBase)
        QtCore.QMetaObject.connectSlotsByName(PrzechwycWysokoscDockWidgetBase)

    def retranslateUi(self, PrzechwycWysokoscDockWidgetBase):
        _translate = QtCore.QCoreApplication.translate
        PrzechwycWysokoscDockWidgetBase.setWindowTitle(_translate("PrzechwycWysokoscDockWidgetBase", "Przechwyć Wysokość GUGiK NMT API"))
        self.lbl_copyrights.setText(_translate("PrzechwycWysokoscDockWidgetBase", "© 2019 <a href=\"http://www.envirosolutions.pl/\">EnviroSolutions Sp. z o.o.</a>"))
        self.label.setText(_translate("PrzechwycWysokoscDockWidgetBase", "Wtyczka pozwala\n"
"na sprawdzenie wysokości terenu\n"
"na podstawie API NMT\n"
"udostępnianego przez GUGiK."))
        self.label_2.setText(_translate("PrzechwycWysokoscDockWidgetBase", "Współrzędne:"))
        self.captureButton.setText(_translate("PrzechwycWysokoscDockWidgetBase", "Przechwytuj"))
        self.label_3.setText(_translate("PrzechwycWysokoscDockWidgetBase", "Wysokość:"))
        self.copyButton.setText(_translate("PrzechwycWysokoscDockWidgetBase", "Kopiuj do schowka"))
        self.lbl_pluginVersion.setText(_translate("PrzechwycWysokoscDockWidgetBase", "Przechwyć Wysokość 1.0"))
        self.lbl_email.setText(_translate("PrzechwycWysokoscDockWidgetBase", "<a href=\"mailto:office@envirosolutions.pl\">office@envirosolutions.pl</a>"))


